### ISSUE TITLE
ld: invalid origin for memory region FLASH

### ISSUE THREAD

**Issue by mnaberez** [noahp/minimal-c-cortex-m#5]
Building 0507e0d650e9001375bc9c7e945242ff258a246e:

```
$ make
arm-none-eabi-gcc -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffunction-sections -fdata-sections -g3 -Wall -Werror -mlittle-endian -mthumb -mthumb-interwork -DENABLE_SEMIHOSTING=1 --specs=rdimon.specs -lc -lrdimon -Tdevices/stm32f407.ld -Wl,--gc-sections,-Map,build/main.elf.map build/main.o build/interrupts.o -o build/main.elf
/usr/local/Cellar/arm-none-eabi-gcc/8-2018-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/8.2.1/../../../../arm-none-eabi/bin/ld: invalid origin for memory region FLASH
collect2: error: ld returned 1 exit status
make: *** [build/main.elf] Error 1
```

I believe the error occurs on at least these versions:

- GNU ld (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 2.31.51.20181213
- GNU ld (GNU Tools for Arm Embedded Processors 8-2019-q3-update) 2.32.0.20190703

The error seems related to [Bug 24289](https://sourceware.org/bugzilla/show_bug.cgi?id=24289) and is caused by lines similar to these in the linker scripts:

https://github.com/noahp/minimal-c-cortex-m/blob/0507e0d650e9001375bc9c7e945242ff258a246e/devices/ambiq-apollo3.ld#L20-L22

A workaround is remove `INTERRUPTS` and have `.interrupts` as the first region within 
`FLASH`.  However, this will lose the padding of `INTERRUPTS`.  If that solution is chosen, the vectors in `startup.c` should be padded out:

https://github.com/noahp/minimal-c-cortex-m/blob/0507e0d650e9001375bc9c7e945242ff258a246e/interrupts.c#L59-L77

Otherwise, code will be written in the vector table area.  That is undesirable but should not cause a running issue unless those interrupts are enabled.

**Comment by noahp** [comment]
Awesome info! thank you for posting it 🤩 Should be fixed up now.
Kind of a bummer of a regression that slipped into those releases, but no big deal.

**Comment by mnaberez** [comment]
> Should be fixed up now.

It builds fine now. ✨ Thanks for the quick fix!
